#!/bin/bash
dependencies="openssl"
f_dependency
function f_cypher_AES256_openssl_base64 {
####################   CRYPT   ####################
echo "crypting file using using AES256_openssl_base64"
f_randpass 256 0
openssl enc -aes-256-cbc -a -salt -pass pass:"$frandom" -in "$directory/$filename" -out "$directory/$filename.crypt"
mv $directory/$filename.crypt $directory/$filename
###################   DECRYPT   ###################
echo "echo \"decrypting layer $layer using using AES_openssl_base64\"" >> $directory/$filename-keys/$layer
echo "openssl enc -d -aes-256-cbc -a -pass pass:\"$frandom\" -in \"$filename\" -out \"$filename.decrypt\"" >> $directory/$filename-keys/$layer
echo "mv $filename.decrypt $filename" >> $directory/$filename-keys/$layer
}
