#!/bin/bash
dependencies="mcrypt"
f_dependency
function f_cypher_XTEA_mcrypt {
####################   CRYPT   ####################
echo "crypting file using with XTEA - mcrypt"
f_randpass 900 0
mcrypt --no-openpgp -q "$directory/$filename" -k "$frandom" -a xtea 2>>/dev/null
mv $directory/$filename.nc $directory/$filename
###################   DECRYPT   ###################
echo "echo \"decrypting layer $layer using using XTEA - mcrypt\"" >> $directory/$filename-keys/$layer
echo "mv $filename $filename.nc" >> $directory/$filename-keys/$layer
echo "mcrypt --no-openpgp -q -d \"$filename.nc\" -k \"$frandom\" -a xtea 2>>/dev/null" >> $directory/$filename-keys/$layer
echo "rm $filename.nc" >> $directory/$filename-keys/$layer
}
